package main

import (
	"praticando/interfaces"
)

func main() {
	// fmt.Println("Hello, World!")
	// variaveis.ExibirVariaveis()
	// controle_fluxo.ControleFluxo()
	// funcoes.ExibirFuncoes()
	// estruturas_dados.ExibirEstruturaDeDados()
	// structs.ExibirStructs()
	// structs_aninhadas.ExibirStructsAninhadas()
	// goroutines.Exibir()
	// goroutines.ChamaChannels()
	// goroutines.ChamaChannels()
	// goroutines.ChamaBuffered()
	// goroutines.ChamarSelect()
	// sintaxe.RetornoLimpo()
	// sintaxe.VariaveisComInicializadores()
	// tiposbasicos.TiposBasicos()
	// sintaxe.Constates()
	// constantes.EvitaMagicaDeCodigo()
	// forfluxo.ForPadrao()
	// forfluxo.ForContinuacao()
	// iffluxo.IfComDeclaracao()
	// formatacoes.Verbos()
	// switchfluxo.SwitchExemplo()
	// switchfluxo.SwitchSemCondicao()
	// deferfluxo.ChamadaComDefer()
	// tiposbasicos.NilTipo()
	// ponteiros.Ponteiros()
	// estruturas_dados.SliceExample()
	// estruturas_dados.SlicesComMake()
	// estruturas_dados.SlicesSlices()
	// metodos.Metodos()
	// metodos.MetodosContinuacao()
	// metodos.MetodosPonteiros()
	// metodos.MetodosPonteirosExplicado()
	// interfaces.Interface()
	// interfaces.InterfacesValores()
	interfaces.InterfacesValoresNil()
}
